# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use the official Python image with a slim variant
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the pyproject.toml file and src directory into the container
COPY pyproject.toml /app/
COPY src /app/src

# Install the dependencies specified in the pyproject.toml
RUN pip install --upgrade pip
RUN pip install hatchling
RUN pip install .

# Set environment variables for LinkedIn credentials
# These should be set during container run or through a Docker secret mechanism
ENV LINKEDIN_EMAIL=your_linkedin_email
ENV LINKEDIN_PASSWORD=your_linkedin_password

# Set the entry point for the container
ENTRYPOINT ["uvicorn", "mcp_linkedin.client:mcp.run", "--host", "0.0.0.0", "--port", "8000"]